### ISSUE TITLE
Build action for ARM64

### ISSUE THREAD

**Issue by joshbowyer** [ReplayDev/Replay#104]
**Is your feature request related to a problem? Please describe.**
Cant install or build on Debian ARM64

**Describe the solution you'd like**
Add flatpak build action for ARM64

**Additional context**
This is an ideal app for Pinephone

**Comment by JulianGro** [comment]
Looks finished to me: https://github.com/ReplayDev/Replay/pull/105

**Comment by nahuelwexd** [comment]
I forgot to close the issue, the action was indeed created in that pull request
